# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to github pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: actions/checkout@v2
      
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: build
      run: |
          npm install
          npm run docs:build
          
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        branch: gh-pages
        folder: .vuepress/dist
